(ns cljs-thread.test.generate
  "Generates temporary runner .cljs files and shadow-cljs build configs.

   Instead of maintaining 5+ hand-written unified runner files, the test
   framework generates a runner namespace tailored to the exact set of
   tests being run. The generated file:

   1. Requires all discovered test namespaces
   2. Exports symbols for anti-DCE
   3. Sets up tier-appropriate prerequisites (slab, worker mesh)
   4. Runs tests via cljs.test

   Shadow-cljs configs are generated as data maps for programmatic compilation."
  (:require [cljs-thread.test.convention :as conv]
            [clojure.java.io :as io]
            [clojure.string :as str]))

;; ---------------------------------------------------------------------------
;; Runner template generation
;; ---------------------------------------------------------------------------

(defn- ns-require-form
  "Generate a :require entry for a test namespace.
   Returns [ns-sym :as alias] where alias prevents DCE."
  [{:keys [ns]}]
  (let [alias (symbol (-> (str ns)
                          (str/replace "." "$")
                          (str/replace "-" "_")))]
    [ns :as alias]))

(defn- gen-pure-runner
  "Generate runner source for :pure tier tests."
  [runner-ns tests {:keys [reporter timeout-ms]}]
  (let [requires (mapv ns-require-form tests)
        ns-syms (mapv :ns tests)]
    (str
     ";; AUTO-GENERATED by cljs-thread.test.generate — do not edit\n"
     "(ns " runner-ns "\n"
     "  (:require\n"
     "   [goog]\n"
     "   [cljs.test :as t]\n"
     "   [cljs-thread.test.tier :as tier]\n"
     (when reporter
       "   [cljs-thread.test.reporter :as reporter]\n")
     (str/join "\n"
       (for [r requires]
         (str "   " (pr-str r))))
     "))\n\n"
     ";; Anti-DCE exports\n"
     (str/join "\n"
       (for [{:keys [ns]} tests]
         (str "(goog/exportSymbol \"" (conv/ns->munged-str ns) "\" " ns ")")))
     "\n\n"
     "(defmethod t/report [::t/default :summary] [{:keys [test pass fail error]}]\n"
     "  (println)\n"
     "  (println (str \"Ran \" test \" tests containing \"\n"
     "                (+ pass fail error) \" assertions.\"))\n"
     "  (println (str fail \" failures, \" error \" errors.\"))\n"
     "  (tier/exit! (if (pos? (+ fail error)) 1 0)))\n\n"
     "(defn main []\n"
     "  (println \"=== cljs-thread Test Runner (:pure tier) ===\")\n"
     "  (t/run-tests\n"
     (str/join "\n"
       (for [ns-sym ns-syms]
         (str "    '" ns-sym)))
     "))\n")))

(defn- gen-slab-runner
  "Generate runner source for :slab tier tests.
   Generates a :begin-test-ns handler that resets slab pools and creates a
   fresh atom-domain before each namespace to prevent overflow OOM from
   accumulated allocations across test namespaces."
  [runner-ns tests {:keys [reporter timeout-ms]}]
  (let [requires (mapv ns-require-form tests)
        ns-syms (mapv :ns tests)]
    (str
     ";; AUTO-GENERATED by cljs-thread.test.generate — do not edit\n"
     "(ns " runner-ns "\n"
     "  (:require\n"
     "   [goog]\n"
     "   [cljs.test :as t]\n"
     "   [cljs-thread.test.tier :as tier]\n"
     (when reporter
       "   [cljs-thread.test.reporter :as reporter]\n")
     (str/join "\n"
       (for [r requires]
         (str "   " (pr-str r))))
     "))\n\n"
     ";; Anti-DCE exports\n"
     (str/join "\n"
       (for [{:keys [ns]} tests]
         (str "(goog/exportSymbol \"" (conv/ns->munged-str ns) "\" " ns ")")))
     "\n\n"
     ;; Recycle atom-domain between every test namespace to prevent OOM
     ;; from accumulated allocations. Skip the first namespace (init-slab!
     ;; just created a fresh domain).
     "(def ^:private first-ns? (atom true))\n\n"
     "(defmethod t/report [::t/default :begin-test-ns] [m]\n"
     "  (if @first-ns?\n"
     "    (reset! first-ns? false)\n"
     "    (do (println \"  Recycling atom-domain...\")\n"
     "        (tier/recycle-default-atom-domain!)))\n"
     "  (println (str \"\\nTesting \" (:ns m))))\n\n"
     "(defmethod t/report [::t/default :summary] [{:keys [test pass fail error]}]\n"
     "  (println)\n"
     "  (println (str \"Ran \" test \" tests containing \"\n"
     "                (+ pass fail error) \" assertions.\"))\n"
     "  (println (str fail \" failures, \" error \" errors.\"))\n"
     "  (tier/update-dom-results! test pass fail error)\n"
     "  (tier/update-dom-status!\n"
     "    (if (zero? (+ fail error)) \"ALL TESTS PASSED\" \"TESTS FAILED\")\n"
     "    (if (zero? (+ fail error)) \"pass\" \"fail\"))\n"
     "  (tier/exit! (if (pos? (+ fail error)) 1 0)))\n\n"
     "(defn- run-suite! []\n"
     "  (-> (tier/init-slab!)\n"
     "      (.then (fn [_]\n"
     "               (println \"Slab allocator initialized.\")\n"
     "               (println)\n"
     "               (t/run-tests\n"
     (str/join "\n"
       (for [ns-sym ns-syms]
         (str "                 '" ns-sym)))
     ")))\n"
     "      (.catch (fn [e]\n"
     "                (println (str \"ERROR: \" (.-message e)))\n"
     "                (tier/exit! 1)))))\n\n"
     "(defn main []\n"
     "  (println \"=== cljs-thread Test Runner (:slab tier) ===\")\n"
     "  (println)\n"
     "  (js/setTimeout\n"
     "    (fn [] (println \"\\nTIMEOUT: Tests exceeded time limit\")\n"
     "          (tier/exit! 1))\n"
     "    " (or timeout-ms 30000) ")\n"
     "  (run-suite!))\n\n"
     "(defn init! []\n"
     "  (tier/update-dom-status! \"Running tests...\" \"running\")\n"
     "  (run-suite!))\n")))

(defn- gen-worker-runner
  "Generate runner source for :worker tier tests."
  [runner-ns tests {:keys [reporter timeout-ms future-count]}]
  (let [requires (mapv ns-require-form tests)
        ns-syms (mapv :ns tests)]
    (str
     ";; AUTO-GENERATED by cljs-thread.test.generate — do not edit\n"
     "(ns " runner-ns "\n"
     "  (:require-macros [cljs-thread.core :refer [in on-when]])\n"
     "  (:require\n"
     "   [goog]\n"
     "   [cljs.test :as t]\n"
     "   [cljs-thread.test.tier-worker :as tw]\n"
     "   [cljs-thread.env :as e]\n"
     (when reporter
       "   [cljs-thread.test.reporter :as reporter]\n")
     (str/join "\n"
       (for [r requires]
         (str "   " (pr-str r))))
     "))\n\n"
     ";; Anti-DCE exports\n"
     (str/join "\n"
       (for [{:keys [ns]} tests]
         (str "(goog/exportSymbol \"" (conv/ns->munged-str ns) "\" " ns ")")))
     "\n\n"
     ";; Report overrides — suppress process.exit on workers\n"
     "(defmethod t/report [:cljs.test/default :begin-test-ns] [m]\n"
     "  (println (str \"\\nTesting \" (:ns m))))\n\n"
     "(defmethod t/report [:cljs.test/default :begin-test-var] [m]\n"
     "  (print (str \"  \" (-> m :var meta :name) \"... \")))\n\n"
     "(defmethod t/report [:cljs.test/default :end-test-var] [_m]\n"
     "  (println \"OK\"))\n\n"
     "(defmethod t/report [:cljs.test/default :fail] [m]\n"
     "  (t/inc-report-counter! :fail)\n"
     "  (println (str \"\\n    FAIL in \" (t/testing-vars-str m)))\n"
     "  (when-let [msg (:message m)] (println (str \"    \" msg)))\n"
     "  (println (str \"    expected: \" (pr-str (:expected m))))\n"
     "  (println (str \"      actual: \" (pr-str (:actual m)))))\n\n"
     "(defmethod t/report [:cljs.test/default :error] [m]\n"
     "  (t/inc-report-counter! :error)\n"
     "  (println (str \"\\n    ERROR in \" (t/testing-vars-str m)))\n"
     "  (when-let [msg (:message m)] (println (str \"    \" msg)))\n"
     "  (println (str \"    \" (pr-str (:actual m)))))\n\n"
     "(defmethod t/report [:cljs.test/default :summary] [m]\n"
     "  (println (str \"\\nRan \" (:test m) \" tests containing \"\n"
     "                (+ (:pass m) (:fail m) (:error m)) \" assertions.\"))\n"
     "  (println (str (:fail m) \" failures, \" (:error m) \" errors.\")))\n\n"
     "(defmethod t/report [:cljs.test/default :end-run-tests] [_m] nil)\n\n"
     "(defn run-tests-on-worker! []\n"
     "  (let [env (-> (t/empty-env)\n"
     (str/join "\n"
       (for [ns-sym ns-syms]
         (str "              (t/run-tests '" ns-sym ")")))
     ")]\n"
     "    (if (t/successful? env) 0 1)))\n\n"
     "(defn- init-main-thread! []\n"
     "  (println \"=== cljs-thread Test Runner (:worker tier) ===\")\n"
     "  (println (str \"Node.js: \" js/process.version))\n"
     "  (js/setTimeout\n"
     "    (fn [] (println \"\\nTIMEOUT: Tests exceeded time limit\")\n"
     "          (js/process.exit 1))\n"
     "    " (or timeout-ms 120000) ")\n"
     "  (tw/init-worker!\n"
     "    :future-count " (or future-count 6) "\n"
     "    :on-ready\n"
     "    (fn []\n"
     "      (tw/dispatch-to-core! run-tests-on-worker!))))\n\n"
     "(defn main []\n"
     "  (if (tw/in-screen?)\n"
     "    (init-main-thread!)\n"
     "    nil))\n")))

;; ---------------------------------------------------------------------------
;; Public API
;; ---------------------------------------------------------------------------

(defn generate-runner-source
  "Generate runner ClojureScript source for the given tests and tier.

   Options:
     :runner-ns     - namespace symbol for the generated runner
     :tier          - :pure, :slab, or :worker
     :reporter      - reporter keyword (nil for default)
     :timeout-ms    - timeout in ms (tier defaults if nil)
     :future-count  - worker pool size (only for :worker tier)"
  [tests {:keys [runner-ns tier reporter timeout-ms future-count]
          :or   {runner-ns 'cljs-thread.test.generated-runner}}]
  (case tier
    :pure   (gen-pure-runner runner-ns tests {:reporter reporter :timeout-ms timeout-ms})
    :slab   (gen-slab-runner runner-ns tests {:reporter reporter :timeout-ms timeout-ms})
    :worker (gen-worker-runner runner-ns tests {:reporter reporter :timeout-ms timeout-ms
                                                 :future-count future-count})))

(defn write-runner!
  "Generate and write a runner .cljs file. Returns the file path."
  [tests opts]
  (let [source (generate-runner-source tests opts)
        ;; Convert ns to path: cljs-thread.test.generated-runner → cljs_thread/test/generated_runner.cljs
        ns-path (-> (str (or (:runner-ns opts) 'cljs-thread.test.generated-runner))
                    (str/replace "." "/")
                    (str/replace "-" "_")
                    (str ".cljs"))
        file-path (str "target/generated-test/" ns-path)]
    (io/make-parents (io/file file-path))
    (spit file-path source)
    file-path))

;; ---------------------------------------------------------------------------
;; Shadow-cljs build config generation
;; ---------------------------------------------------------------------------

(defn generate-shadow-config
  "Generate a shadow-cljs build config map for the test run.
   Used with the programmatic API (shadow.cljs.devtools.api/compile*).

   Options:
     :build-id    - keyword build ID (default :test-run)
     :tier        - :pure, :slab, or :worker
     :runner-ns   - namespace symbol for the runner
     :output-path - JS output path
     :opt-level   - :none, :basic, or :advanced
     :source-paths - extra source paths"
  [{:keys [build-id tier runner-ns output-path opt-level source-paths]
    :or   {build-id    :test-run
           runner-ns   'cljs-thread.test.generated-runner
           output-path "target/test-run/test.js"
           opt-level   :none}}]
  (let [base {:build-id build-id
              :target   :node-script
              :main     (symbol (str runner-ns) "main")
              :output-to output-path
              :compiler-options {:load-tests true}
              :source-paths (into ["src" "test"] (or source-paths []))}]
    (cond-> base
      (= opt-level :basic)
      (assoc-in [:compiler-options :optimizations] :simple)

      ;; :advanced uses default Closure optimizations
      ;; :none uses no optimizations (development)
      )))

(defn generate-browser-shadow-config
  "Generate a shadow-cljs browser build config for the test run."
  [{:keys [build-id tier runner-ns output-dir opt-level source-paths]
    :or   {build-id   :test-browser-run
           runner-ns  'cljs-thread.test.generated-runner
           output-dir "target/test-run-browser"
           opt-level  :none}}]
  (let [base {:build-id build-id
              :target     :browser
              :output-dir output-dir
              :asset-path "."
              :modules    {:main {:init-fn (symbol (str runner-ns) "init!")}}
              :compiler-options {:load-tests true}
              :source-paths (into ["src" "test"] (or source-paths []))
              :js-options {:resolve {"worker_threads" {:target :browser :global "null"}
                                     "wabt"           {:target :browser :global "null"}}}}]
    (cond-> base
      (= opt-level :basic)
      (assoc-in [:compiler-options :optimizations] :simple))))
