(ns cljs-thread.eve.deftype-proto.wasm
  "WASM Slab Allocator Memory Module.

   Unlike eve.wasm-mem which uses a single shared WebAssembly.Memory,
   this module manages MULTIPLE WebAssembly.Memory instances — one per slab.
   Each slab gets its own WASM module instance backed by its own SAB.

   ARCHITECTURE:
   ═══════════════════════════════════════════════════════════════

   ┌────────────────────────────────────────────────────────────┐
   │   Slab 0 (32B)  │ Slab 1 (64B) │ ... │ Slab 5 (1024B)   │
   │   WASM Instance  │ WASM Instance│     │ WASM Instance     │
   │   SAB + Bitmap   │ SAB + Bitmap │     │ SAB + Bitmap      │
   └────────────────────────────────────────────────────────────┘
                         │
                         ▼
   ┌────────────────────────────────────────────────────────────┐
   │           slab_bitmap.wat (shared WASM module)             │
   │   bitmap_find_free_simd  │  bitmap_alloc_cas               │
   │   bitmap_free            │  bitmap_count_free_simd         │
   │   memcpy                 │  bytes_equal                    │
   └────────────────────────────────────────────────────────────┘

   Each slab creates a WebAssembly.Memory with shared:true.
   The same WASM module (slab_bitmap.wasm) is instantiated once per slab,
   with the slab's memory as the import.")

;;=============================================================================
;; Module State
;;=============================================================================

(defonce ^:private wasm-compiled-module (atom nil))

;; Pre-compiled WASM binary (1036 bytes) generated by: node scripts/compile-slab-wasm.js
;; Source: slab-wat-source below (slab bitmap: find_free, alloc_cas, free, count_free, memcpy, bytes_equal)
;; NOTE: bitmap_free now returns 1 if bit was set (valid free), 0 if already clear (double-free)
(def ^:private slab-wasm-bytes
  (js/Uint8Array. #js [ 0x00 0x61 0x73 0x6d 0x01 0x00 0x00 0x00 0x01 0x14 0x03 0x60 0x03 0x7f 0x7f 0x7f
 0x01 0x7f 0x60 0x02 0x7f 0x7f 0x01 0x7f 0x60 0x03 0x7f 0x7f 0x7f 0x00 0x02 0x12
 0x01 0x03 0x65 0x6e 0x76 0x06 0x6d 0x65 0x6d 0x6f 0x72 0x79 0x02 0x03 0x01 0x80
 0x80 0x01 0x03 0x08 0x07 0x00 0x00 0x01 0x01 0x01 0x02 0x00 0x07 0x7d 0x07 0x10
 0x62 0x69 0x74 0x6d 0x61 0x70 0x5f 0x66 0x69 0x6e 0x64 0x5f 0x66 0x72 0x65 0x65
 0x00 0x00 0x15 0x62 0x69 0x74 0x6d 0x61 0x70 0x5f 0x66 0x69 0x6e 0x64 0x5f 0x66
 0x72 0x65 0x65 0x5f 0x73 0x69 0x6d 0x64 0x00 0x01 0x10 0x62 0x69 0x74 0x6d 0x61
 0x70 0x5f 0x61 0x6c 0x6c 0x6f 0x63 0x5f 0x63 0x61 0x73 0x00 0x02 0x0b 0x62 0x69
 0x74 0x6d 0x61 0x70 0x5f 0x66 0x72 0x65 0x65 0x00 0x03 0x16 0x62 0x69 0x74 0x6d
 0x61 0x70 0x5f 0x63 0x6f 0x75 0x6e 0x74 0x5f 0x66 0x72 0x65 0x65 0x5f 0x73 0x69
 0x6d 0x64 0x00 0x04 0x06 0x6d 0x65 0x6d 0x63 0x70 0x79 0x00 0x05 0x0b 0x62 0x79
 0x74 0x65 0x73 0x5f 0x65 0x71 0x75 0x61 0x6c 0x00 0x06 0x0a 0xce 0x06 0x07 0x7b
 0x01 0x07 0x7f 0x20 0x02 0x41 0x05 0x76 0x21 0x03 0x20 0x02 0x41 0x1f 0x71 0x21
 0x04 0x20 0x01 0x41 0x1f 0x6a 0x41 0x05 0x76 0x21 0x05 0x02 0x40 0x03 0x40 0x20
 0x03 0x20 0x05 0x4f 0x0d 0x01 0x20 0x00 0x20 0x03 0x41 0x02 0x74 0x6a 0xfe 0x10
 0x02 0x00 0x21 0x06 0x20 0x06 0x41 0x7f 0x73 0x21 0x07 0x20 0x04 0x04 0x40 0x20
 0x07 0x41 0x7f 0x20 0x04 0x74 0x71 0x21 0x07 0x41 0x00 0x21 0x04 0x0b 0x20 0x07
 0x04 0x40 0x20 0x07 0x68 0x21 0x08 0x20 0x03 0x41 0x05 0x74 0x20 0x08 0x6a 0x21
 0x09 0x20 0x09 0x20 0x01 0x49 0x04 0x40 0x20 0x09 0x0f 0x0b 0x0b 0x20 0x03 0x41
 0x01 0x6a 0x21 0x03 0x0c 0x00 0x0b 0x0b 0x41 0x7f 0x0b 0xf3 0x01 0x03 0x02 0x7f
 0x03 0x7b 0x03 0x7f 0x20 0x02 0x41 0x03 0x76 0x41 0x70 0x71 0x21 0x03 0x20 0x01
 0x41 0x07 0x6a 0x41 0x03 0x76 0x21 0x04 0x41 0x7f 0xfd 0x0f 0x21 0x07 0x02 0x40
 0x03 0x40 0x20 0x03 0x41 0x10 0x6a 0x20 0x04 0x4b 0x0d 0x01 0x20 0x00 0x20 0x03
 0x6a 0xfd 0x00 0x04 0x00 0x21 0x05 0x20 0x05 0x20 0x07 0xfd 0x51 0x21 0x06 0x20
 0x06 0xfd 0x53 0x04 0x40 0x20 0x06 0xfd 0x1b 0x00 0x21 0x08 0x20 0x08 0x04 0x40
 0x20 0x03 0x41 0x03 0x74 0x20 0x08 0x68 0x6a 0x21 0x0a 0x20 0x0a 0x20 0x01 0x49
 0x04 0x40 0x20 0x0a 0x0f 0x0b 0x0b 0x20 0x06 0xfd 0x1b 0x01 0x21 0x08 0x20 0x08
 0x04 0x40 0x20 0x03 0x41 0x03 0x74 0x41 0x20 0x20 0x08 0x68 0x6a 0x6a 0x21 0x0a
 0x20 0x0a 0x20 0x01 0x49 0x04 0x40 0x20 0x0a 0x0f 0x0b 0x0b 0x20 0x06 0xfd 0x1b
 0x02 0x21 0x08 0x20 0x08 0x04 0x40 0x20 0x03 0x41 0x03 0x74 0x41 0xc0 0x00 0x20
 0x08 0x68 0x6a 0x6a 0x21 0x0a 0x20 0x0a 0x20 0x01 0x49 0x04 0x40 0x20 0x0a 0x0f
 0x0b 0x0b 0x20 0x06 0xfd 0x1b 0x03 0x21 0x08 0x20 0x08 0x04 0x40 0x20 0x03 0x41
 0x03 0x74 0x41 0xe0 0x00 0x20 0x08 0x68 0x6a 0x6a 0x21 0x0a 0x20 0x0a 0x20 0x01
 0x49 0x04 0x40 0x20 0x0a 0x0f 0x0b 0x0b 0x0b 0x20 0x03 0x41 0x10 0x6a 0x21 0x03
 0x0c 0x00 0x0b 0x0b 0x20 0x00 0x20 0x01 0x20 0x03 0x41 0x03 0x74 0x10 0x00 0x0b
 0x4e 0x01 0x04 0x7f 0x20 0x00 0x20 0x01 0x41 0x05 0x76 0x41 0x02 0x74 0x6a 0x21
 0x02 0x41 0x01 0x20 0x01 0x41 0x1f 0x71 0x74 0x21 0x03 0x03 0x40 0x20 0x02 0xfe
 0x10 0x02 0x00 0x21 0x04 0x20 0x04 0x20 0x03 0x71 0x04 0x40 0x41 0x00 0x0f 0x0b
 0x20 0x04 0x20 0x03 0x72 0x21 0x05 0x20 0x02 0x20 0x04 0x20 0x05 0xfe 0x48 0x02
 0x00 0x20 0x04 0x46 0x04 0x40 0x41 0x01 0x0f 0x0b 0x0c 0x00 0x0b 0x00 0x0b 0x30
 0x01 0x03 0x7f 0x20 0x00 0x20 0x01 0x41 0x05 0x76 0x41 0x02 0x74 0x6a 0x21 0x02
 0x20 0x01 0x41 0x1f 0x71 0x21 0x03 0x20 0x02 0x41 0x01 0x20 0x03 0x74 0x41 0x7f
 0x73 0xfe 0x2c 0x02 0x00 0x21 0x04 0x20 0x04 0x20 0x03 0x76 0x41 0x01 0x71 0x0b
 0x8e 0x01 0x03 0x03 0x7f 0x01 0x7b 0x01 0x7f 0x41 0x00 0x21 0x02 0x41 0x00 0x21
 0x04 0x20 0x01 0x41 0x07 0x6a 0x41 0x03 0x76 0x21 0x03 0x02 0x40 0x03 0x40 0x20
 0x02 0x41 0x10 0x6a 0x20 0x03 0x4b 0x0d 0x01 0x20 0x00 0x20 0x02 0x6a 0xfd 0x00
 0x04 0x00 0x21 0x05 0x20 0x04 0x20 0x05 0xfd 0x1b 0x00 0x69 0x20 0x05 0xfd 0x1b
 0x01 0x69 0x6a 0x20 0x05 0xfd 0x1b 0x02 0x69 0x20 0x05 0xfd 0x1b 0x03 0x69 0x6a
 0x6a 0x6a 0x21 0x04 0x20 0x02 0x41 0x10 0x6a 0x21 0x02 0x0c 0x00 0x0b 0x0b 0x02
 0x40 0x03 0x40 0x20 0x02 0x41 0x04 0x6a 0x20 0x03 0x4b 0x0d 0x01 0x20 0x00 0x20
 0x02 0x6a 0x28 0x02 0x00 0x21 0x06 0x20 0x04 0x20 0x06 0x69 0x6a 0x21 0x04 0x20
 0x02 0x41 0x04 0x6a 0x21 0x02 0x0c 0x00 0x0b 0x0b 0x20 0x01 0x20 0x04 0x6b 0x0b
 0x59 0x01 0x01 0x7f 0x41 0x00 0x21 0x03 0x02 0x40 0x03 0x40 0x20 0x03 0x41 0x10
 0x6a 0x20 0x02 0x4b 0x0d 0x01 0x20 0x00 0x20 0x03 0x6a 0x20 0x01 0x20 0x03 0x6a
 0xfd 0x00 0x04 0x00 0xfd 0x0b 0x04 0x00 0x20 0x03 0x41 0x10 0x6a 0x21 0x03 0x0c
 0x00 0x0b 0x0b 0x02 0x40 0x03 0x40 0x20 0x03 0x20 0x02 0x4f 0x0d 0x01 0x20 0x00
 0x20 0x03 0x6a 0x20 0x01 0x20 0x03 0x6a 0x2d 0x00 0x00 0x3a 0x00 0x00 0x20 0x03
 0x41 0x01 0x6a 0x21 0x03 0x0c 0x00 0x0b 0x0b 0x0b 0x71 0x01 0x01 0x7f 0x41 0x00
 0x21 0x03 0x02 0x40 0x03 0x40 0x20 0x03 0x41 0x10 0x6a 0x20 0x02 0x4b 0x0d 0x01
 0x41 0xff 0xff 0x03 0x20 0x00 0x20 0x03 0x6a 0xfd 0x00 0x04 0x00 0x20 0x01 0x20
 0x03 0x6a 0xfd 0x00 0x04 0x00 0xfd 0x23 0xfd 0x64 0x47 0x04 0x40 0x41 0x00 0x0f
 0x0b 0x20 0x03 0x41 0x10 0x6a 0x21 0x03 0x0c 0x00 0x0b 0x0b 0x02 0x40 0x03 0x40
 0x20 0x03 0x20 0x02 0x4f 0x0d 0x01 0x20 0x00 0x20 0x03 0x6a 0x2d 0x00 0x00 0x20
 0x01 0x20 0x03 0x6a 0x2d 0x00 0x00 0x47 0x04 0x40 0x41 0x00 0x0f 0x0b 0x20 0x03
 0x41 0x01 0x6a 0x21 0x03 0x0c 0x00 0x0b 0x0b 0x41 0x01 0x0b]))
(defonce wasm-ready (atom false))

;; Array of slab instances: #js [{:memory :module :exports :i32 :u8 :dv} ...]
;; Indexed by slab class (0-5), slot 6 reserved for overflow (legacy SAB)
(defonce ^:private slab-instances (atom #js [nil nil nil nil nil nil nil]))

;;=============================================================================
;; Constants
;;=============================================================================

(def ^:const PAGE_SIZE 65536)     ;; WASM page size (64KB)
(def ^:const MAX_PAGES 16384)     ;; Max 1GB per slab

;;=============================================================================
;; WAT Source (inline, compiled at runtime)
;;=============================================================================
;; In production this would be pre-compiled to a .wasm binary.
;; For development, we compile from WAT using wabt or the WebAssembly API.

(def ^:private slab-wat-source
  "(module
  (import \"env\" \"memory\" (memory 1 16384 shared))

  ;; bitmap_find_free — scalar scan
  (func $bitmap_find_free (export \"bitmap_find_free\")
        (param $bm_offset i32) (param $total_bits i32) (param $start_bit i32)
        (result i32)
    (local $word_idx i32)
    (local $bit_in_word i32)
    (local $word_count i32)
    (local $word i32)
    (local $inverted i32)
    (local $bit_pos i32)
    (local $abs_bit i32)
    (local.set $word_idx (i32.shr_u (local.get $start_bit) (i32.const 5)))
    (local.set $bit_in_word (i32.and (local.get $start_bit) (i32.const 31)))
    (local.set $word_count
      (i32.shr_u (i32.add (local.get $total_bits) (i32.const 31)) (i32.const 5)))
    (block $not_found
      (loop $next_word
        (br_if $not_found
          (i32.ge_u (local.get $word_idx) (local.get $word_count)))
        (local.set $word
          (i32.atomic.load
            (i32.add (local.get $bm_offset)
                     (i32.shl (local.get $word_idx) (i32.const 2)))))
        (local.set $inverted (i32.xor (local.get $word) (i32.const -1)))
        (if (local.get $bit_in_word)
          (then
            (local.set $inverted
              (i32.and (local.get $inverted)
                       (i32.shl (i32.const -1) (local.get $bit_in_word))))
            (local.set $bit_in_word (i32.const 0))))
        (if (local.get $inverted)
          (then
            (local.set $bit_pos (i32.ctz (local.get $inverted)))
            (local.set $abs_bit
              (i32.add (i32.shl (local.get $word_idx) (i32.const 5))
                       (local.get $bit_pos)))
            (if (i32.lt_u (local.get $abs_bit) (local.get $total_bits))
              (then (return (local.get $abs_bit))))))
        (local.set $word_idx (i32.add (local.get $word_idx) (i32.const 1)))
        (br $next_word)))
    (i32.const -1))

  ;; bitmap_find_free_simd — SIMD scan
  (func $bitmap_find_free_simd (export \"bitmap_find_free_simd\")
        (param $bm_offset i32) (param $total_bits i32) (param $start_bit i32)
        (result i32)
    (local $byte_offset i32)
    (local $bm_byte_size i32)
    (local $vec v128)
    (local $inv v128)
    (local $all_ones v128)
    (local $lane_word i32)
    (local $bit_in_lane i32)
    (local $abs_bit i32)
    (local.set $byte_offset
      (i32.and (i32.shr_u (local.get $start_bit) (i32.const 3))
               (i32.const -16)))
    (local.set $bm_byte_size
      (i32.shr_u (i32.add (local.get $total_bits) (i32.const 7)) (i32.const 3)))
    (local.set $all_ones (i8x16.splat (i32.const -1)))
    (block $simd_done
      (loop $simd_loop
        (br_if $simd_done
          (i32.gt_u (i32.add (local.get $byte_offset) (i32.const 16))
                    (local.get $bm_byte_size)))
        (local.set $vec
          (v128.load (i32.add (local.get $bm_offset) (local.get $byte_offset))))
        (local.set $inv (v128.xor (local.get $vec) (local.get $all_ones)))
        (if (v128.any_true (local.get $inv))
          (then
            ;; Lane 0
            (local.set $lane_word (i32x4.extract_lane 0 (local.get $inv)))
            (if (local.get $lane_word)
              (then
                (local.set $abs_bit
                  (i32.add (i32.shl (local.get $byte_offset) (i32.const 3))
                           (i32.ctz (local.get $lane_word))))
                (if (i32.lt_u (local.get $abs_bit) (local.get $total_bits))
                  (then (return (local.get $abs_bit))))))
            ;; Lane 1
            (local.set $lane_word (i32x4.extract_lane 1 (local.get $inv)))
            (if (local.get $lane_word)
              (then
                (local.set $abs_bit
                  (i32.add (i32.shl (local.get $byte_offset) (i32.const 3))
                           (i32.add (i32.const 32) (i32.ctz (local.get $lane_word)))))
                (if (i32.lt_u (local.get $abs_bit) (local.get $total_bits))
                  (then (return (local.get $abs_bit))))))
            ;; Lane 2
            (local.set $lane_word (i32x4.extract_lane 2 (local.get $inv)))
            (if (local.get $lane_word)
              (then
                (local.set $abs_bit
                  (i32.add (i32.shl (local.get $byte_offset) (i32.const 3))
                           (i32.add (i32.const 64) (i32.ctz (local.get $lane_word)))))
                (if (i32.lt_u (local.get $abs_bit) (local.get $total_bits))
                  (then (return (local.get $abs_bit))))))
            ;; Lane 3
            (local.set $lane_word (i32x4.extract_lane 3 (local.get $inv)))
            (if (local.get $lane_word)
              (then
                (local.set $abs_bit
                  (i32.add (i32.shl (local.get $byte_offset) (i32.const 3))
                           (i32.add (i32.const 96) (i32.ctz (local.get $lane_word)))))
                (if (i32.lt_u (local.get $abs_bit) (local.get $total_bits))
                  (then (return (local.get $abs_bit))))))))
        (local.set $byte_offset (i32.add (local.get $byte_offset) (i32.const 16)))
        (br $simd_loop)))
    ;; Tail
    (call $bitmap_find_free
      (local.get $bm_offset) (local.get $total_bits)
      (i32.shl (local.get $byte_offset) (i32.const 3))))

  ;; bitmap_alloc_cas — CAS to claim a free bit
  (func $bitmap_alloc_cas (export \"bitmap_alloc_cas\")
        (param $bm_offset i32) (param $bit_idx i32)
        (result i32)
    (local $word_offset i32)
    (local $bit_mask i32)
    (local $old_word i32)
    (local $new_word i32)
    (local.set $word_offset
      (i32.add (local.get $bm_offset)
               (i32.shl (i32.shr_u (local.get $bit_idx) (i32.const 5))
                        (i32.const 2))))
    (local.set $bit_mask
      (i32.shl (i32.const 1)
               (i32.and (local.get $bit_idx) (i32.const 31))))
    (loop $retry
      (local.set $old_word (i32.atomic.load (local.get $word_offset)))
      (if (i32.and (local.get $old_word) (local.get $bit_mask))
        (then (return (i32.const 0))))
      (local.set $new_word (i32.or (local.get $old_word) (local.get $bit_mask)))
      (if (i32.eq
            (i32.atomic.rmw.cmpxchg (local.get $word_offset)
                                     (local.get $old_word)
                                     (local.get $new_word))
            (local.get $old_word))
        (then (return (i32.const 1))))
      (br $retry))
    (unreachable))

  ;; bitmap_free — clear a bit, return 1 if was allocated, 0 if already free
  ;; This prevents double-free from corrupting the free-count
  (func $bitmap_free (export \"bitmap_free\")
        (param $bm_offset i32) (param $bit_idx i32)
        (result i32)
    (local $word_offset i32)
    (local $bit_pos i32)
    (local $old_word i32)
    (local.set $word_offset
      (i32.add (local.get $bm_offset)
               (i32.shl (i32.shr_u (local.get $bit_idx) (i32.const 5))
                        (i32.const 2))))
    (local.set $bit_pos
      (i32.and (local.get $bit_idx) (i32.const 31)))
    ;; Atomically clear the bit and capture the old value
    (local.set $old_word
      (i32.atomic.rmw.and
        (local.get $word_offset)
        (i32.xor (i32.shl (i32.const 1) (local.get $bit_pos))
                 (i32.const -1))))
    ;; Return 1 if bit was set in old_word (valid free), 0 if already clear (double-free)
    (i32.and
      (i32.shr_u (local.get $old_word) (local.get $bit_pos))
      (i32.const 1)))

  ;; bitmap_count_free_simd
  (func $bitmap_count_free_simd (export \"bitmap_count_free_simd\")
        (param $bm_offset i32) (param $total_bits i32)
        (result i32)
    (local $byte_offset i32)
    (local $bm_byte_size i32)
    (local $allocated_count i32)
    (local $vec v128)
    (local $word i32)
    (local.set $byte_offset (i32.const 0))
    (local.set $allocated_count (i32.const 0))
    (local.set $bm_byte_size
      (i32.shr_u (i32.add (local.get $total_bits) (i32.const 7)) (i32.const 3)))
    (block $simd_done
      (loop $simd_loop
        (br_if $simd_done
          (i32.gt_u (i32.add (local.get $byte_offset) (i32.const 16))
                    (local.get $bm_byte_size)))
        (local.set $vec
          (v128.load (i32.add (local.get $bm_offset) (local.get $byte_offset))))
        (local.set $allocated_count
          (i32.add (local.get $allocated_count)
            (i32.add
              (i32.add
                (i32.popcnt (i32x4.extract_lane 0 (local.get $vec)))
                (i32.popcnt (i32x4.extract_lane 1 (local.get $vec))))
              (i32.add
                (i32.popcnt (i32x4.extract_lane 2 (local.get $vec)))
                (i32.popcnt (i32x4.extract_lane 3 (local.get $vec)))))))
        (local.set $byte_offset (i32.add (local.get $byte_offset) (i32.const 16)))
        (br $simd_loop)))
    (block $scalar_done
      (loop $scalar_loop
        (br_if $scalar_done
          (i32.gt_u (i32.add (local.get $byte_offset) (i32.const 4))
                    (local.get $bm_byte_size)))
        (local.set $word
          (i32.load (i32.add (local.get $bm_offset) (local.get $byte_offset))))
        (local.set $allocated_count
          (i32.add (local.get $allocated_count) (i32.popcnt (local.get $word))))
        (local.set $byte_offset (i32.add (local.get $byte_offset) (i32.const 4)))
        (br $scalar_loop)))
    (i32.sub (local.get $total_bits) (local.get $allocated_count)))

  ;; memcpy
  (func $memcpy (export \"memcpy\") (param $dst i32) (param $src i32) (param $len i32)
    (local $i i32)
    (local.set $i (i32.const 0))
    (block $simd_done
      (loop $simd_loop
        (br_if $simd_done
          (i32.gt_u (i32.add (local.get $i) (i32.const 16)) (local.get $len)))
        (v128.store
          (i32.add (local.get $dst) (local.get $i))
          (v128.load (i32.add (local.get $src) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 16)))
        (br $simd_loop)))
    (block $scalar_done
      (loop $scalar_loop
        (br_if $scalar_done (i32.ge_u (local.get $i) (local.get $len)))
        (i32.store8
          (i32.add (local.get $dst) (local.get $i))
          (i32.load8_u (i32.add (local.get $src) (local.get $i))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $scalar_loop))))

  ;; bytes_equal
  (func $bytes_equal (export \"bytes_equal\")
        (param $p1 i32) (param $p2 i32) (param $len i32) (result i32)
    (local $i i32)
    (local.set $i (i32.const 0))
    (block $simd_done
      (loop $simd_loop
        (br_if $simd_done
          (i32.gt_u (i32.add (local.get $i) (i32.const 16)) (local.get $len)))
        (if (i32.ne (i32.const 65535)
              (i8x16.bitmask
                (i8x16.eq
                  (v128.load (i32.add (local.get $p1) (local.get $i)))
                  (v128.load (i32.add (local.get $p2) (local.get $i))))))
          (then (return (i32.const 0))))
        (local.set $i (i32.add (local.get $i) (i32.const 16)))
        (br $simd_loop)))
    (block $scalar_done
      (loop $scalar_loop
        (br_if $scalar_done (i32.ge_u (local.get $i) (local.get $len)))
        (if (i32.ne
              (i32.load8_u (i32.add (local.get $p1) (local.get $i)))
              (i32.load8_u (i32.add (local.get $p2) (local.get $i))))
          (then (return (i32.const 0))))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $scalar_loop)))
    (i32.const 1))
)")

;;=============================================================================
;; WASM Module Compilation & Instantiation
;;=============================================================================

(defn- compile-wasm-module!
  "Compile the slab bitmap WASM module.
   Uses pre-compiled bytes (works everywhere including browser workers).
   Falls back to runtime WAT compilation via wabt in Node.js if bytes fail.
   Returns a Promise<WebAssembly.Module> or Promise<nil> on failure."
  []
  (if @wasm-compiled-module
    (js/Promise.resolve @wasm-compiled-module)
    ;; Primary path: use pre-compiled WASM bytes (no external deps needed)
    (-> (js/WebAssembly.compile slab-wasm-bytes)
        (.then (fn [mod]
                 (reset! wasm-compiled-module mod)
                 mod))
        (.catch (fn [_e]
                  ;; Fallback: runtime WAT compilation via wabt (Node.js only)
                  (if-not (exists? js/require)
                    nil
                    (-> (js/Promise.
                          (fn [resolve reject]
                            (try
                              (let [wabt-mod (js/require "wabt")]
                                (.then (wabt-mod)
                                  (fn [^js wabt]
                                    (try
                                      (let [^js parsed (.parseWat wabt "slab_bitmap.wat" slab-wat-source
                                                     #js {:simd true :threads true :atomics true
                                                          :shared-memory true})
                                            _ (.resolveNames parsed)
                                            _ (.validate parsed #js {:simd true :threads true
                                                                     :shared-memory true})
                                            ^js binary (.toBinary parsed #js {})
                                            bytes (.-buffer binary)]
                                        (.then (js/WebAssembly.compile bytes)
                                          (fn [mod]
                                            (reset! wasm-compiled-module mod)
                                            (resolve mod))
                                          reject))
                                      (catch :default e
                                        (reject e))))))
                              (catch :default e
                                (reject e)))))
                        (.catch (fn [e]
                                  (println "[slab-wasm] WAT compilation failed:" (.-message e))
                                  (println "[slab-wasm] Falling back to JS bitmap operations")
                                  nil)))))))))


(defn- instantiate-for-memory!
  "Create a new WASM instance using the pre-compiled module and a specific memory.
   Returns the exports object."
  [compiled-module wasm-memory]
  (-> (js/WebAssembly.instantiate compiled-module
        #js {"env" #js {"memory" wasm-memory}})
      (.then (fn [instance]
               (.-exports instance)))))

;;=============================================================================
;; Slab Instance Management
;;=============================================================================

(defn create-slab-memory
  "Create memory for a slab.
   When WASM module is available, creates a WebAssembly.Memory (growable).
   Otherwise, returns a plain SharedArrayBuffer (sufficient for JS fallback)."
  [total-bytes]
  (let [pages (js/Math.ceil (/ total-bytes PAGE_SIZE))
        actual-pages (max pages 1)
        actual-bytes (* actual-pages PAGE_SIZE)]
    (if @wasm-compiled-module
      ;; WASM path: need WebAssembly.Memory for module instantiation
      (let [max-pages (min MAX_PAGES (* actual-pages 4))]
        (js/WebAssembly.Memory.
          #js {:initial actual-pages
               :maximum max-pages
               :shared true}))
      ;; JS fallback path: plain SharedArrayBuffer avoids virtual memory overhead
      (js/SharedArrayBuffer. actual-bytes))))

(defn init-slab-instance!
  "Initialize a WASM instance for a slab class.
   Registers typed array views synchronously so the JS-fallback bitmap
   operations work immediately.  WASM exports are added asynchronously
   once the module is compiled + instantiated.
   Returns a Promise that resolves to the slab instance map."
  [class-idx wasm-memory]
  (let [buf (if (instance? js/SharedArrayBuffer wasm-memory)
              wasm-memory
              (.-buffer wasm-memory))
        instance {:memory wasm-memory
                  :exports nil
                  :i32 (js/Int32Array. buf)
                  :u8 (js/Uint8Array. buf)
                  :dv (js/DataView. buf)
                  :class-idx class-idx}]
    ;; Register immediately so alloc/batch_alloc can use JS fallbacks
    (aset @slab-instances class-idx instance)
    ;; Upgrade to WASM exports asynchronously
    (-> (compile-wasm-module!)
        (.then (fn [compiled-module]
                 (when (and compiled-module (instance? js/WebAssembly.Memory wasm-memory))
                   (instantiate-for-memory! compiled-module wasm-memory))))
        (.then (fn [exports]
                 (when exports
                   (let [upgraded (assoc instance :exports exports)]
                     (aset @slab-instances class-idx upgraded)
                     upgraded)))))))

(defn get-slab-instance
  "Get the slab instance for a given class index."
  [class-idx]
  (aget @slab-instances class-idx))

;;=============================================================================
;; Bitmap Operations (JS fallbacks for when WASM isn't ready)
;;=============================================================================

(defn- js-bitmap-find-free
  "JS fallback: scan bitmap for first free bit starting from start-bit."
  [i32-view bm-int32-offset total-bits start-bit]
  (let [word-count (unsigned-bit-shift-right (+ total-bits 31) 5)]
    (loop [word-idx (unsigned-bit-shift-right start-bit 5)
           bit-in-word (bit-and start-bit 31)]
      (if (>= word-idx word-count)
        -1
        (let [word (js/Atomics.load i32-view (+ bm-int32-offset word-idx))
              inverted (bit-xor word -1)
              ;; Mask out bits below start position in first word
              masked (if (pos? bit-in-word)
                       (bit-and inverted (bit-shift-left -1 bit-in-word))
                       inverted)]
          (if (not (zero? masked))
            (let [;; JS bit-shift-right uses sign-extending, we need ctz
                  ;; ctz via: (& -n n) isolates lowest set bit, then clz gives position
                  ;; Simpler: iterate bits
                  bit-pos (loop [b 0]
                            (if (>= b 32) 32
                              (if (not (zero? (bit-and masked (bit-shift-left 1 b))))
                                b
                                (recur (inc b)))))
                  abs-bit (+ (bit-shift-left word-idx 5) bit-pos)]
              (if (< abs-bit total-bits)
                abs-bit
                -1))
            (recur (inc word-idx) 0)))))))

(defn- js-bitmap-alloc-cas!
  "JS fallback: CAS to set a bitmap bit from 0 to 1.
   Returns true on success, false if bit was already set."
  [i32-view bm-int32-offset bit-idx]
  (let [word-idx (+ bm-int32-offset (unsigned-bit-shift-right bit-idx 5))
        bit-mask (bit-shift-left 1 (bit-and bit-idx 31))]
    (loop []
      (let [old-word (js/Atomics.load i32-view word-idx)]
        (if (not (zero? (bit-and old-word bit-mask)))
          false ;; Already allocated
          (let [new-word (bit-or old-word bit-mask)]
            (if (== old-word (js/Atomics.compareExchange i32-view word-idx old-word new-word))
              true
              (recur))))))))

(defn- js-bitmap-free!
  "JS fallback: clear a bitmap bit (free a block).
   Returns true if bit was set (valid free), false if already clear (double-free)."
  [i32-view bm-int32-offset bit-idx]
  (let [word-idx (+ bm-int32-offset (unsigned-bit-shift-right bit-idx 5))
        bit-pos (bit-and bit-idx 31)
        clear-mask (bit-xor (bit-shift-left 1 bit-pos) -1)
        ;; Atomic AND returns old value
        old-word (js/Atomics.and i32-view word-idx clear-mask)]
    ;; Return true if bit was set in old-word
    (not (zero? (bit-and (unsigned-bit-shift-right old-word bit-pos) 1)))))

;;=============================================================================
;; Public API: Bitmap Operations
;;=============================================================================

(defn bitmap-find-free
  "Find the first free block in a slab's bitmap.
   Uses WASM+SIMD when available, JS fallback otherwise.
   Returns block index or -1."
  [class-idx bm-byte-offset total-bits start-bit]
  (let [inst (get-slab-instance class-idx)]
    (if (and inst (:exports inst))
      ;; WASM path — try SIMD first, fallback to scalar
      (let [^js exports (:exports inst)]
        (if (.-bitmap_find_free_simd exports)
          (.bitmap_find_free_simd exports bm-byte-offset total-bits start-bit)
          (.bitmap_find_free exports bm-byte-offset total-bits start-bit)))
      ;; JS fallback
      (let [i32-view (:i32 inst)
            bm-int32-offset (unsigned-bit-shift-right bm-byte-offset 2)]
        (js-bitmap-find-free i32-view bm-int32-offset total-bits start-bit)))))

(defn bitmap-alloc-cas!
  "Atomically claim a block in a slab's bitmap (set bit 0→1).
   Returns true on success, false if already taken."
  [class-idx bm-byte-offset bit-idx]
  (let [inst (get-slab-instance class-idx)]
    (if (and inst (:exports inst))
      (== 1 (.bitmap_alloc_cas ^js (:exports inst) bm-byte-offset bit-idx))
      ;; JS fallback
      (js-bitmap-alloc-cas! (:i32 inst) (unsigned-bit-shift-right bm-byte-offset 2) bit-idx))))

(defn bitmap-free!
  "Free a block in a slab's bitmap (clear bit 1→0).
   Returns true if block was allocated (valid free), false if already free (double-free)."
  [class-idx bm-byte-offset bit-idx]
  (let [inst (get-slab-instance class-idx)]
    (if (and inst (:exports inst))
      (== 1 (.bitmap_free ^js (:exports inst) bm-byte-offset bit-idx))
      ;; JS fallback
      (js-bitmap-free! (:i32 inst) (unsigned-bit-shift-right bm-byte-offset 2) bit-idx))))

(defn bitmap-count-free
  "Count free blocks in a slab's bitmap."
  [class-idx bm-byte-offset total-bits]
  (let [inst (get-slab-instance class-idx)]
    (if (and inst (:exports inst) (.-bitmap_count_free_simd ^js (:exports inst)))
      (.bitmap_count_free_simd ^js (:exports inst) bm-byte-offset total-bits)
      ;; JS fallback: just count allocated bits
      (let [i32-view (:i32 inst)
            bm-int32-offset (unsigned-bit-shift-right bm-byte-offset 2)
            word-count (unsigned-bit-shift-right (+ total-bits 31) 5)]
        (loop [i 0 allocated 0]
          (if (>= i word-count)
            (- total-bits allocated)
            (let [word (js/Atomics.load i32-view (+ bm-int32-offset i))
                  ;; JS popcount via Kernighan's trick
                  pc (loop [v word c 0]
                       (if (zero? v) c
                         (recur (bit-and v (dec v)) (inc c))))]
              (recur (inc i) (+ allocated pc)))))))))

;;=============================================================================
;; Data Access Helpers
;;=============================================================================

(defn slab-u8-view
  "Get the Uint8Array view for a slab."
  [class-idx]
  (:u8 (get-slab-instance class-idx)))

(defn slab-i32-view
  "Get the Int32Array view for a slab."
  [class-idx]
  (:i32 (get-slab-instance class-idx)))

(defn slab-data-view
  "Get the DataView for a slab."
  [class-idx]
  (:dv (get-slab-instance class-idx)))

(defn slab-buffer
  "Get the SharedArrayBuffer for a slab."
  [class-idx]
  (let [mem (:memory (get-slab-instance class-idx))]
    (if (instance? js/SharedArrayBuffer mem)
      mem
      (.-buffer mem))))

;;=============================================================================
;; Worker-Side Instance Registration (from existing SABs)
;;=============================================================================

(defn register-slab-instance-from-sab!
  "Register an existing SharedArrayBuffer as a slab instance (for workers).
   Workers receive SABs from the main thread but don't have WASM memory objects.
   Creates views from the SAB and registers with nil WASM exports
   (bitmap operations will use JS fallbacks)."
  [class-idx sab]
  (let [instance {:memory nil
                  :exports nil
                  :i32 (js/Int32Array. sab)
                  :u8 (js/Uint8Array. sab)
                  :dv (js/DataView. sab)
                  :class-idx class-idx}]
    (aset @slab-instances class-idx instance)
    instance))

;;=============================================================================
;; Overflow Instance (class 6 — legacy SAB)
;;=============================================================================

(defn register-overflow-instance!
  "Register the legacy (original eve.atom) SAB as slab instance 6.
   This allows slab-qualified offsets with class_idx=6 to resolve
   to the legacy SAB's DataView/Uint8Array/Int32Array views.
   No WASM module is associated — bitmap ops don't apply to overflow."
  [sab]
  (let [instance {:memory nil
                  :exports nil
                  :i32 (js/Int32Array. sab)
                  :u8 (js/Uint8Array. sab)
                  :dv (js/DataView. sab)
                  :class-idx 6}]
    (aset @slab-instances 6 instance)
    instance))

;;=============================================================================
;; Init
;;=============================================================================

(defn init!
  "Initialize the slab WASM system. Compiles the module.
   Slab instances are created later via init-slab-instance!."
  []
  (-> (compile-wasm-module!)
      (.then (fn [mod]
               (when mod
                 (reset! wasm-ready true)
                 (println "[slab-wasm] Module compiled successfully"))
               mod))
      (.catch (fn [e]
                (println "[slab-wasm] Init failed:" (.-message e))
                nil))))

(defn ready?
  "Returns true if WASM slab module is compiled and ready."
  []
  @wasm-ready)
